services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: schedule_bot_db
    ports:
      - "6105:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schedule_bot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/schedule_bot_db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
